### ISSUE TITLE
Elixir 1.3 warning

### ISSUE THREAD

**Issue by akurkin** [CargoSense/vex#30] opened 2016-07-21 17:32 UTC
hey guys,
found this little warning whilst installing and using vex for the first time:

```
Compiling 20 files (.ex)
warning: the variable "validations" is unsafe as it has been set inside a case/cond/receive/if/&&/||. Please explicitly return the variable value instead. For example:

    case int do
      1 -> atom = :one
      2 -> atom = :two
    end

should be written as

    atom =
      case int do
        1 -> :one
        2 -> :two
      end

Unsafe variable found at:
  lib/vex.ex:25
```

**Comment by areski** [comment] 2016-07-25 16:20
Same here but exrm_deb seems to be using version vex0.5
https://github.com/johnhamelink/exrm_deb/blob/master/mix.exs#L55

**Comment by areski** [comment] 2016-07-25 16:26
The problem is still on the last version of vex:

    warning: the variable "validations" is unsafe as it has been set inside a case/cond/receive/if/&&/||. Please explicitly return the variable value instead. For example:

        case int do
          1 -> atom = :one
          2 -> atom = :two
        end

    should be written as

        atom =
          case int do
            1 -> :one
            2 -> :two
          end

    Unsafe variable found at:
      lib/vex.ex:35

**Comment by benwilson512** [comment] 2016-08-31 21:55
Fixed in master.

**Closed by benwilson512** 2016-08-31 21:55 UTC
